CREATE DATABASE TIENDABD;

-- Tabla PERSONA
CREATE TABLE PERSONA (
    IDPERSONA INT IDENTITY (1,1) NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    APELLIDO NVARCHAR(50) NOT NULL,
    TELEFONO NVARCHAR(50) NULL,
    CI NVARCHAR(10) NOT NULL,
    CORREO NVARCHAR(100) NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDPERSONA)
);

-- Tabla USUARIO
CREATE TABLE USUARIO (
    IDUSUARIO INT IDENTITY (1,1) NOT NULL,
    IDPERSONA INT NOT NULL,
    NOMBREUSER NVARCHAR(50) NULL,
    CONTRASEÑA NVARCHAR(50) NULL,
    FECHAREG DATE NULL,
    PRIMARY KEY (IDUSUARIO),
    FOREIGN KEY (IDPERSONA) REFERENCES PERSONA(IDPERSONA)
);

-- Tabla USUARIOROL
CREATE TABLE USUARIOROL (
    IDUSUARIOROL INT IDENTITY (1,1) NOT NULL,
    IDUSUARIO INT NOT NULL,
    IDROL INT NOT NULL,
    FECHAASIGNA DATE NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDUSUARIOROL),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    FOREIGN KEY (IDROL) REFERENCES ROL(IDROL)
);

-- Tabla ROL
CREATE TABLE ROL (
    IDROL INT IDENTITY (1,1) NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDROL)
);

-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    IDCLIENTE INT IDENTITY (1,1) NOT NULL,
    IDPERSONA INT NOT NULL,
    TIPOCLIENTE NVARCHAR(50) NULL,
    CODIGOCLIE NVARCHAR(20) NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDCLIENTE),
    FOREIGN KEY (IDPERSONA) REFERENCES PERSONA(IDPERSONA)
);

-- Tabla VENTA
CREATE TABLE VENTA (
    IDVENTA INT IDENTITY (1,1) NOT NULL,
    IDCLIENTE INT NOT NULL,
    IDVENDEDOR INT NOT NULL,
    FECHA DATE NULL,
    TOTAL DECIMAL(10, 2) NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDVENTA),
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
    FOREIGN KEY (IDVENDEDOR) REFERENCES USUARIO(IDUSUARIO)
);

-- Tabla DETALLEVENTA
CREATE TABLE DETALLEVENTA (
    IDDETALLEVENTA INT IDENTITY (1,1) NOT NULL,
    IDVENTA INT NOT NULL,
    IDPRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIOVENTA DECIMAL(10, 2) NULL,
    SUBTOTAL DECIMAL(10, 2) NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDDETALLEVENTA),
    FOREIGN KEY (IDVENTA) REFERENCES VENTA(IDVENTA),
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO)
);

-- Tabla DETALLEINGRESO
CREATE TABLE DETALLEINGRESO (
    IDDETALLEING INT IDENTITY (1,1) NOT NULL,
    IDPRODUCTO INT NOT NULL,
    IDINGRESO INT NOT NULL,
    FECHAVENC DATE NULL,
    CANTIDAD INT NOT NULL,
    PRECIOCOSTO DECIMAL(10, 2) NULL,
    PRECIOVENTA DECIMAL(10, 2) NULL,
    SUBTOTAL DECIMAL(10, 2) NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDDETALLEING),
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO),
    FOREIGN KEY (IDINGRESO) REFERENCES INGRESO(IDINGRESO)
);

-- Tabla INGRESO
CREATE TABLE INGRESO (
    IDINGRESO INT IDENTITY (1,1) NOT NULL,
    IDPROVEEDOR INT NOT NULL,
    FECHAINGRESO DATE NULL,
    TOTAL DECIMAL(10, 2) NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDINGRESO),
    FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR(IDPROVEEDOR)
);

-- Tabla PRODUCTO
CREATE TABLE PRODUCTO (
    IDPRODUCTO INT IDENTITY (1,1) NOT NULL,
    IDTIPOPROD INT NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    CODIGOBARRA NVARCHAR(20) NULL,
    IDMARCA INT NOT NULL,
    UNIDAD NVARCHAR(20) NULL,
    DESCRIPCION NVARCHAR(MAX) NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDPRODUCTO)
);

-- Tabla PROVEE
CREATE TABLE PROVEE (
    IDPROVEE INT IDENTITY (1,1) NOT NULL,
    IDPRODUCTO INT NOT NULL,
    IDPROVEEDOR INT NOT NULL,
    FECHA DATE NULL,
    PRECIO DECIMAL(10, 2) NULL,
    PRIMARY KEY (IDPROVEE),
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO),
    FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR(IDPROVEEDOR)
);

-- Tabla PROVEEDOR
CREATE TABLE PROVEEDOR (
    IDPROVEEDOR INT IDENTITY (1,1) NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    TELEFONO NVARCHAR(20) NULL,
    DIRECCION NVARCHAR(100) NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDPROVEEDOR)
);

-- Tabla TIPOPROD
CREATE TABLE TIPOPROD (
    IDTIPOPROD INT IDENTITY (1,1) NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDTIPOPROD)
);

-- Tabla MARCA
CREATE TABLE MARCA (
    IDMARCA INT IDENTITY (1,1) NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDMARCA)
);

-- Relaciones entre las tablas
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY (IDPERSONA) REFERENCES PERSONA(IDPERSONA);
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_PERSONA FOREIGN KEY (IDPERSONA) REFERENCES PERSONA(IDPERSONA);
ALTER TABLE VENTA ADD CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);
ALTER TABLE VENTA ADD CONSTRAINT FK_VENTA_USUARIO FOREIGN KEY (IDVENDEDOR) REFERENCES USUARIO(IDUSUARIO);
ALTER TABLE DETALLEVENTA ADD CONSTRAINT FK_DETALLEVENTA_VENTA FOREIGN KEY (IDVENTA) REFERENCES VENTA(IDVENTA);
ALTER TABLE DETALLEVENTA ADD CONSTRAINT FK_DETALLEVENTA_PRODUCTO FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);
ALTER TABLE DETALLEINGRESO ADD CONSTRAINT FK_DETALLEINGRESO_PRODUCTO FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);
ALTER TABLE DETALLEINGRESO ADD CONSTRAINT FK_DETALLEINGRESO_INGRESO FOREIGN KEY (IDINGRESO) REFERENCES INGRESO(IDINGRESO);
ALTER TABLE INGRESO ADD CONSTRAINT FK_INGRESO_PROVEEDOR FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR(IDPROVEEDOR);
ALTER TABLE PROVEE ADD CONSTRAINT FK_PROVEE_PRODUCTO FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);
ALTER TABLE PROVEE ADD CONSTRAINT FK_PROVEE_PROVEEDOR FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR(IDPROVEEDOR);
ALTER TABLE ROL ADD CONSTRAINT FK_ROL_USUARIOROL FOREIGN KEY (IDROL) REFERENCES USUARIOROL(IDROL);
ALTER TABLE USUARIOROL ADD CONSTRAINT FK_USUARIOROL_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO);
ALTER TABLE USUARIOROL ADD CONSTRAINT FK_USUARIOROL_ROL FOREIGN KEY (IDROL) REFERENCES ROL(IDROL);
